name: test

on:
    pull_request:
      branches: ["*"]
    push:
        branches: [main]

jobs:

  test:
      runs-on: self-hosted
      steps:
          - uses: actions/checkout@v4
          - run: |
              CUDA_HOME=/usr/local/cuda
              pip install -r requirements-dev.txt --break-system-packages --user
              pip uninstall torchmorph --yes --break-system-packages
              python setup.py install --user
          - run: |
              ORIGINAL=$(pwd)
              cd /tmp
              pytest $ORIGINAL/test